# Generated by Django 5.0 on 2024-01-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_model',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(default=None, upload_to='files/')),
            ],
        ),
    ]
